### ISSUE TITLE
Effect of Gun Law Reviews

### ISSUE THREAD

**Issue by khayk5ay** [heyakshayhere/Hamoye_stage_B#13]
So I've gone through the notebook severally just trying to wrap my head around everything that's going on. A thought just came to me. We see that for some states, there is an increase in the gun law reviews on a yearly basis to demonstrate the strictness of the legislature in tackling gun violence in these states. 
However, is it possible to measure what effect these increase or decrease in reviews as the case may be, affects the gun violence incidents in the coming year? or even in that year (depending on how the count of gun law reviews was obtained for each year). 
That is, does the increase in reviews for a particular year see a decrease in the violence of the upcoming year, and vice versa? @heyakshayhere

**Comment by heyakshayhere** [comment]
The numbers are taken from the internet just to get the more insights of the data and so that we can get more clear picture
